#image: "docker.betterdoctor.com:443/bd-webdrone:latest"
#image: "ruby:2.2.1"
image: "jussikole/bd-webdrone"
script:
  - ./.drone/build.sh
notify:
  email:
    recipients:
      - jussi@betterdoctor.com