#image: docker.betterdoctor.com:443/ci-test-project
image: ruby:2.2.1
script:
  - ./.drone/build.sh
deploy:
  bash:
    script:
      - ./.drone/deploy.sh
notify:
  email:
    recipients:
      - jussi@betterdoctor.com